/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pkgVues;

import java.util.Iterator;
import org.hibernate.Query;
import org.hibernate.Transaction;
import pkgEntites.Etablissement;
import pkgEntites.Offre;
import pkgEntites.OffreId;
import pkgEntites.TypeChambre;

/**
 *
 * @author Maxence
 */
public class jpHebergementAjout extends javax.swing.JPanel {
    private boolean bCharge = false;
    private String sEtablissementId = "";
    private String sTypeChambreId = "";
    /**
     * Creates new form jpHebergementAjout
     */
    public jpHebergementAjout() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCbListeEtablissement = new javax.swing.JComboBox();
        jCbListeTypeChambre = new javax.swing.JComboBox();
        jbtAjout = new javax.swing.JButton();
        jlblQuantite = new javax.swing.JLabel();
        jtxtModif = new javax.swing.JTextField();

        jCbListeEtablissement.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCbListeEtablissement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCbListeEtablissementMouseClicked(evt);
            }
        });
        jCbListeEtablissement.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbListeEtablissementItemStateChanged(evt);
            }
        });
        jCbListeEtablissement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbListeEtablissementActionPerformed(evt);
            }
        });

        jCbListeTypeChambre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCbListeTypeChambre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCbListeTypeChambreMouseClicked(evt);
            }
        });
        jCbListeTypeChambre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbListeTypeChambreItemStateChanged(evt);
            }
        });
        jCbListeTypeChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbListeTypeChambreActionPerformed(evt);
            }
        });

        jbtAjout.setText("Ajouter");
        jbtAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAjoutActionPerformed(evt);
            }
        });

        jlblQuantite.setText("Nombre Chambres");

        jtxtModif.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCbListeTypeChambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jCbListeEtablissement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtAjout)
                        .addGap(87, 87, 87))))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlblQuantite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbListeEtablissement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbListeTypeChambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblQuantite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtAjout)
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCbListeEtablissementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCbListeEtablissementMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbListeEtablissementMouseClicked

    private void jCbListeEtablissementItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbListeEtablissementItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbListeEtablissementItemStateChanged
     public void chargeListeEtablissement(){
        String sReq = "From Etablissement";
        Query q = jfPrincipal.getSession().createQuery(sReq);
        jCbListeEtablissement.removeAllItems();
        Iterator eta = q.iterate();
        while(eta.hasNext())
           {
           Etablissement unEtablissement = (Etablissement) eta.next();
           jCbListeEtablissement.addItem(unEtablissement.getEtaNom());
           }
        bCharge = true;
    }
     public void chargeListeTypeChambre(){
        String sReq = "From TypeChambre ";
        Query q = jfPrincipal.getSession().createQuery(sReq);
        jCbListeTypeChambre.removeAllItems();
        Iterator eta = q.iterate();
        while(eta.hasNext())
           {
           TypeChambre unTypeChambre = (TypeChambre) eta.next();
           jCbListeTypeChambre.addItem(unTypeChambre.getTchLibelle());
           }
        bCharge = true;
    } 
     
     
    private void jCbListeEtablissementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbListeEtablissementActionPerformed
        if(bCharge)
        {
            String sReq = "from Etablissement Where Eta_Nom = ?";
            Query q = jfPrincipal.getSession().createQuery(sReq);
            q.setParameter(0, jCbListeEtablissement.getSelectedItem().toString());
            Etablissement unEtablissement = (Etablissement) q.uniqueResult();
            sEtablissementId = unEtablissement.getEtaId();
           // chargeTable(sEtablissementId);
        }
    }//GEN-LAST:event_jCbListeEtablissementActionPerformed

    private void jCbListeTypeChambreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCbListeTypeChambreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbListeTypeChambreMouseClicked

    private void jCbListeTypeChambreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbListeTypeChambreItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbListeTypeChambreItemStateChanged

    private void jCbListeTypeChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbListeTypeChambreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbListeTypeChambreActionPerformed

    private void jbtAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAjoutActionPerformed
        sEtablissementId = jCbListeEtablissement.getSelectedItem().toString();
        sTypeChambreId = jCbListeTypeChambre.getSelectedItem().toString();
        
        Offre unOffre = new Offre();
        OffreId unOffreId = new OffreId(sEtablissementId, sTypeChambreId);
        System.out.println(unOffreId.toString());
        unOffre.setId(unOffreId);
        unOffre.setOffNbChambres(Integer.parseInt(jtxtModif.getText()));

       
       // Transaction tx = jfPrincipal.getSession().beginTransaction();
       // jfPrincipal.getSession().save(unOffre);
       // tx.commit();

    }//GEN-LAST:event_jbtAjoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCbListeEtablissement;
    private javax.swing.JComboBox jCbListeTypeChambre;
    private javax.swing.JButton jbtAjout;
    private javax.swing.JLabel jlblQuantite;
    private javax.swing.JTextField jtxtModif;
    // End of variables declaration//GEN-END:variables
}
