/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVues;

import javax.swing.JOptionPane;
import org.hibernate.Transaction;
import pkgEntites.TypeChambre;

/**
 *
 * @author Chloé
 */
public class jpTypeChambreAjout extends javax.swing.JPanel {

    /**
     * Creates new form jpTypeChambreAjout
     */
    public jpTypeChambreAjout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltypechambre = new java.awt.Label();
        jbtnajout = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        jtxtid = new javax.swing.JTextField();
        lbllibelle = new javax.swing.JLabel();
        jtxtlibelle = new javax.swing.JTextField();

        lbltypechambre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbltypechambre.setText("Type chambre");

        jbtnajout.setText("Ajouter");
        jbtnajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnajoutActionPerformed(evt);
            }
        });

        lblid.setText("Id");

        lbllibelle.setText("Libellé");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbltypechambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jbtnajout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllibelle)
                            .addComponent(lblid))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtid, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtlibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbltypechambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid)
                    .addComponent(jtxtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllibelle)
                    .addComponent(jtxtlibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jbtnajout)
                .addGap(135, 135, 135))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnajoutActionPerformed
        // TODO add your handling code here:
      //  Session session = HibernateUtil.getSessionFactory().openSession();
        TypeChambre unNewTypeChambre = new TypeChambre();
        unNewTypeChambre.setTchId(jtxtid.getText());
        unNewTypeChambre.setTchLibelle(jtxtlibelle.getText());
        Transaction tx = jfPrincipal.getSession().beginTransaction();
        jfPrincipal.getSession().save(unNewTypeChambre);
        tx.commit();
        JOptionPane.showMessageDialog(null, "Nouveau type chambre ajouté avec succès !");
    }//GEN-LAST:event_jbtnajoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnajout;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtlibelle;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lbllibelle;
    private java.awt.Label lbltypechambre;
    // End of variables declaration//GEN-END:variables
}
